//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        public int id { get; set; }
        public int q1 { get; set; }
        public int q2 { get; set; }
        public int q3 { get; set; }
        public int q4 { get; set; }
        public string gender { get; set; }
        public string cabin_type { get; set; }
        public string departure { get; set; }
        public string arrival { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Answer Answer1 { get; set; }
        public virtual Answer Answer2 { get; set; }
        public virtual Answer Answer3 { get; set; }
    }
}
